### ISSUE TITLE
Cannot clone into theme folder using git submodule

### ISSUE THREAD

**Issue by Dalesttn** [StaticMania/hugo-apsho#2]
Ran git submodule and got this error
Cloning into 'C:/WebDevelopment/cyberaas/themes/apsho'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by souravzzz** [comment]
Fixed in [PR ](https://github.com/StaticMania/hugo-apsho/pull/3)

**Comment by fluttered** [comment]
You can use https instead of ssh.

`git submodule add https://github.com/StaticMania/hugo-apsho.git themes/apsho`

**Comment by thomaspoignant** [comment]
The PR #3 is about this issue.
